apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:Jl2cyN5O/DOCI7K5UPCDr6+/OCIKXt1ykH9zPVtcbKkcoNMC26TYYirPpf/HKIwpMvkEmUQBR9AokYoPBHbu83bfT2cI/DX+hA09yVprvDvl8RSCXlHAuaznRZQcqcOPzH6SgZj4tnJo29rz6nJfqBpsbPDo4QuAlW06/Te+cGzNMlmLErLXW4OjejVFI15fFZ/l/Oa1022TjwR0UuxqhTbJz4799GUaTQRWWVUsKJq0u0hU2AIfeRJYaMRC/i6al52QeYUBnyCDc6UG15QvTdyEOmUmcBClSx1+jKZLs5x7lOfF2DTADM4C1ww=,iv:tCJLuIHIhd4yRIOPHOGgDn3Gd24ITwBcZQB+P+CmPBo=,tag:d02U7+Twz+ZGaMGiXqto5Q==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
sops:
  age:
    - recipient: age1xlze8jpc6ue654d4lp5ceg5ra8k7rvr607952vxhdme7chhqm4dsk9j6nl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR0pvbkJuVExqMlhEWEZq
        OXg5UEhIN09RRTkvNVpBUnFVM25JVnhzcFRrCmZHb2FqMU9iZHVveS8xUkw5a2Na
        WlRqandDay9jcWp3bEF3U25aQkQrT1EKLS0tIExFQnd5NFk4bU84R3pMTW9DTUlp
        a05EamZYaERxL2VOVnFGQnNLR0REU1kKolTAXdnRYfbY6fluIlpgCoo8m4Q4Ev1U
        ZEarWBhJFJyeDV2mt9SvE/fjQs1EmlydixWM8JsSD6TSyuw9vv/1lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T12:45:33Z"
  mac: ENC[AES256_GCM,data:p5EPwScB02efrbW7/FSaXSrx/o9QQdefPUUMNlYT0kqv1IcnIZUGz7Mzy76wtjxnY/U358e4pEKXk7Qb8DW/M22yueav/jCXS8xLS9jHUq1eR4gMMjXmvxjob00mA6IwQQCSJgbuC4g3AkpCDs8wUIr6sCw1ZhGRxJV+Y9CMlmI=,iv:v/JfqKbRhReVYGkqrU+EgKPSY0OGkkcdkCJ2N7beLlA=,tag:6abm20T9rSQM5scvuJ7P6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
