apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  template:
    spec:
      nodeSelector:
        storage: ssd
      containers:
        - name: mealie
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-postgres
spec:
  template:
    spec:
      nodeSelector:
        storage: ssd
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
