apiVersion: v1
kind: Secret
metadata:
    name: mealie-postgres-secret
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yUT9BNxRd9EM,iv:bs6KaSrKl2eXycqDw8qOmeYLHYUX39RkMSVhvnXOV5s=,tag:vVN7Dsxq995YoJzWYivgEA==,type:str]
sops:
    age:
        - recipient: age1xlze8jpc6ue654d4lp5ceg5ra8k7rvr607952vxhdme7chhqm4dsk9j6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2FjZXhJcEhiRVJTWHpO
            M0tHaGR4MzcwQkxiUEw5R0FqK3QycWNSL0dnCm01MWFKL2VJN25kdThCQU1nVHE3
            cmltZmlFenN6ODBzbGJkalhmcDdZbHMKLS0tIHd4dk5FVUpVdUY5OENQK1NCMEEw
            a1p2bUlzMDdpMVBxMTN5UWIyVUo3VHcKZu9DwldkypzgT+BXOmGrAk3NAyXArfXc
            fG2IyV/1TmNBpt41KVCJECZOzAzRoBWdgO92OCYq14Zo7eXRL1mCQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T11:55:57Z"
    mac: ENC[AES256_GCM,data:vumFuTjjrXnFdnWLSa3RTW2CgCA1bGEoWIUk0okQ6cd333VMOV3CZmPqRiCqNLaE/+z9csA5Fgtrf/Syqg6nmKo6ebERjar41JXzZIY7PMCOuV6SkzAqKsiRMMAzDn2cjKlHWA/153ncnmfRyMIRRB1KGWTMPn3U7agTZM4zoBg=,iv:XvWmEgM8+mjQ/oJQzjdWQTUw5sYLCDRSX1hThN2j0F0=,tag:bZGUJQS69BTyqoKEiUYWcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
