apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:QF8eXLL6SpKELL51fsvyPxbaAIEAeF9aFxrddUSJsX8msRKDEQYoAyI8b5Ngf1Xx4aEzw21bZH5A+7ALEy9S+J6kv0WtJEJ0/+GOi5r3gp1E0gelFlaT2PF2R+VlpRNccmFwt8cbD4uW7L+7lt2kY9rr63/wap9JJ1YKAjNEsfekOHVJdnKEfAPRTwmEDJB81t4+zehzRzA1ZjWnzE2ZwNP+2wl2iSMYR5lfyfYWd+aosXkMDqYEBUzrXoBTxp2RLuOQBQohNz78TDpmPVNPt0r026I7Cxe6Ll6wg8/nQgelpYDxj0Djl8ZuPYY=,iv:GTMzhQ53A9jSPpyvi54x4WCqJsnT4RTT9rmP2RQHybQ=,tag:zVB8ZeHRUjuazF6KPXxcyA==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
sops:
  age:
    - recipient: age1xlze8jpc6ue654d4lp5ceg5ra8k7rvr607952vxhdme7chhqm4dsk9j6nl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOUM2ckJoaUg1emFwbGdQ
        WGlWeTIvbWRKR2R2Qzg4SDUxNjZuN2duaWw0CnFySERNM3lWY1Z2dXc3RUF1bGVr
        cW9uOFpVZGF0SzhjbFVpdmt0aGdWM1kKLS0tIFpkVTNPTzJlZW96VG1kZGJDT0lU
        YTdkVG5wNHE5WjdTWnRKaWlqbmdLY1kKesBz65Eoc2qpcbIFpUQsKpZR3T/vzE4x
        HfTkF5cFS8PYohqEjnJcGtwBHltOGnuiZZk/DzXuEnunYHST7mCt5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T11:00:47Z"
  mac: ENC[AES256_GCM,data:J/F3tHlv00JavQl8t9tU7MbS4SoSCkuvksgSMJO5YSPyym3cQbchJ+9QKQDZFOXdAKL3BQTDUfwFpq4isYcfNAtg9vfdF8WctiluXbF0Tuv2k1f1n5/s2evuAsd20j9GPTxp0+16swG4PMJ1lTEc//lAgvq6dBip2/JqC208QI4=,iv:VOaIsVuEMPMP6dGUXgTYaHEe6qdU2ZH+IPQaTwIZUtg=,tag:Z3g+eDUzxcrBj6ATpDuh8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
