apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "39.0.5"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    deployment:
      kind: DaemonSet
    ingressClass:
      name: traefik
      enabled: true
      isDefaultClass: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    ports:
      web:
        exposedPort: 80
        hostPort: 80
      websecure:
        exposedPort: 443
        hostPort: 443
    service:
      type: ClusterIP
