apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:R0W9xoizZTs9mdmkv5fCjS0xCFQYND0MxT3yKc41yDtDAS2unoAdW9gD1F3xJFp99ncMDybLFAk=,iv:1dJFRfz4Ztl6AnJ/YEa3pMxeWgqUOcQLaFtI1n5LwIM=,tag:/gmUFGDX07KzYb8Qtck+bA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1xlze8jpc6ue654d4lp5ceg5ra8k7rvr607952vxhdme7chhqm4dsk9j6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eGJqU3V3cFptTHB5QURp
            dmJXTmRGNkNaVDRoZVJveWl0QzlZa1Z5SWdvCmV5T3FsbVVFaWlTMGhpL3BzcVJP
            WndFNmJPQkt2NFRENERGRDBENTQ0bG8KLS0tIDFXR1JFZUU5SHBUZW0xR0YrTUZr
            TGphTklIMVZSblVKZSsydWg5RmRHam8KczwK1SlQJeEUin7RxDVp3dgYh9HuM/8c
            Yq6UOcbzfecjMjH1kZsXx7Xq3nyrKEKOrAjaTZo5vw/IcgZ/HpUb3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T02:41:17Z"
    mac: ENC[AES256_GCM,data:Kv5w+RJvvduykPXzXXcjnR72KdAFo6QRtZ5fdajxNYHV/3NLBrvaYs4LzVuc1SVaXVy37It2FW0HOarVDcR/DJJlrTY7niCYT1eBb33Gd+wOgKCkhZsi7j1X2BqrK7CnNdfhsdYLTLLk1OTPWAZmy1AgJ6eZFv0yzra6LLAGPpw=,iv:M9ctzaQLO4t22g59JHfR5DgFk+wXsGCVxr8RbFoa+dQ=,tag:VoKga9xkceErZChedAEZ/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
